apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-exporter
  template:
    metadata:
      labels:
        app: metrics-exporter
    spec:
      containers:
      - image: test:2
        name: metrics-exporter
        ports:
        - containerPort: 6440